version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://todo:password@db:5432/todo
    depends_on:
      - db